services:
  app:
    build: 
      context: .
    command: > 
      sh -c "python manage.py makemigrations && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - . :/src

  db:
    image: postgresql:15-lpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=cv
      - POSTGRES_USER=cv_admin
      - POSTGRES_PASSWORD=cv_admin.1234
