# Generated by Django 4.2.7 on 2023-11-06 18:30

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='authoremodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='status_education',
            field=models.CharField(choices=[('studying', 'studying'), ('done', 'done')], default='studying', verbose_name='studying'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 18, 30, 5, 325654, tzinfo=datetime.timezone.utc)),
        ),
    ]
