# Generated by Django 4.2.7 on 2023-11-06 19:01

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_aboutmemodels_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='from_date',
            new_name='at_data',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='up_to_date',
            new_name='to_data',
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='authoremodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='status_project',
            field=models.CharField(choices=[('start', 'start'), ('doing', 'doing'), ('complate', 'complate')], default='complate', max_length=8, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 6, 19, 1, 30, 411144, tzinfo=datetime.timezone.utc)),
        ),
    ]
